example/example/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('pyfb_company.urls', namespace='pyfb_company')),
]

pyfb_company/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from rest_framework import routers

from . import api
from . import views


app_name = 'pyfb-company'

router = routers.DefaultRouter()
router.register(r'company', api.CompanyViewSet)
router.register(r'customer', api.CustomerViewSet)
router.register(r'provider', api.ProviderViewSet)
router.register(r'companybalancehistory', api.CompanyBalanceHistoryViewSet)

urlpatterns = (
    # urls for Django Rest Framework API
    path('api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for Company
    path('pyfb_company/company/', views.CompanyListView.as_view(), name='pyfb_company_company_list'),
    path('pyfb_company/company/create/', views.CompanyCreateView.as_view(), name='pyfb_company_company_create'),
    path('pyfb_company/company/detail/<slug:slug>/', views.CompanyDetailView.as_view(), name='pyfb_company_company_detail'),
    path('pyfb_company/company/update/<slug:slug>/', views.CompanyUpdateView.as_view(), name='pyfb_company_company_update'),
)

urlpatterns += (
    # urls for Customer
    path('pyfb_company/customer/', views.CustomerListView.as_view(), name='pyfb_company_customer_list'),
    path('pyfb_company/customer/create/', views.CustomerCreateView.as_view(), name='pyfb_company_customer_create'),
    path('pyfb_company/customer/detail/<int:pk>/', views.CustomerDetailView.as_view(), name='pyfb_company_customer_detail'),
    path('pyfb_company/customer/update/<int:pk>/', views.CustomerUpdateView.as_view(), name='pyfb_company_customer_update'),
)

urlpatterns += (
    # urls for Provider
    path('pyfb_company/provider/', views.ProviderListView.as_view(), name='pyfb_company_provider_list'),
    path('pyfb_company/provider/create/', views.ProviderCreateView.as_view(), name='pyfb_company_provider_create'),
    path('pyfb_company/provider/detail/<int:pk>/', views.ProviderDetailView.as_view(), name='pyfb_company_provider_detail'),
    path('pyfb_company/provider/update/<int:pk>/', views.ProviderUpdateView.as_view(), name='pyfb_company_provider_update'),
)

urlpatterns += (
    # urls for CompanyBalanceHistory
    path('pyfb_company/companybalancehistory/', views.CompanyBalanceHistoryListView.as_view(), name='pyfb_company_companybalancehistory_list'),
    path('pyfb_company/companybalancehistory/create/', views.CompanyBalanceHistoryCreateView.as_view(), name='pyfb_company_companybalancehistory_create'),
    path('pyfb_company/companybalancehistory/detail/<int:pk>/', views.CompanyBalanceHistoryDetailView.as_view(), name='pyfb_company_companybalancehistory_detail'),
    path('pyfb_company/companybalancehistory/update/<int:pk>/', views.CompanyBalanceHistoryUpdateView.as_view(), name='pyfb_company_companybalancehistory_update'),
)

pyfb_company/models.py
# -*- coding: utf-8 -*-
from django.urls import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from django_extensions.db.fields import AutoSlugField

from model_utils.models import TimeStampedModel


class Company(TimeStampedModel):

    # Fields
    name = models.CharField(_(u'name'), max_length=200, unique=True, help_text=_(u"company name - must be unique"))
    slug = AutoSlugField(populate_from='name', blank=True)
    address = models.CharField(_(u'address'), max_length=64, help_text=_(u"address"))
    contact_name = models.CharField(_(u'contact name'), max_length=30, help_text=_(u"contact name"))
    contact_phone = models.CharField(_(u'contact phone'), max_length=30, help_text=_(u"contact phone number"))
#    customer_balance = models.DecimalField(_(u'customer balance'), max_digits=12, decimal_places=6, default=0, help_text=_(u"actual customer balance."))
#    supplier_balance = models.DecimalField(_(u'provider balance'), max_digits=12, decimal_places=6, default=0, help_text=_(u"actual provider balance."))
#    customer_balance_update = models.BooleanField(_(u"customer balance is updated after each call"), default=True)
#    provider_balance_update = models.BooleanField(_(u"provider balance is updated after each call"), default=False)

    class Meta:
        db_table = 'pyfb_company'
        ordering = ('name',)
        verbose_name = _(u'company')
        verbose_name_plural = _(u'companies')

    def __str__(self):
        return u'%s' % self.name

    def get_absolute_url(self):
        return reverse('pyfb-company:pyfb_company_company_detail', args=(self.slug,))


    def get_update_url(self):
        return reverse('pyfb-company:pyfb_company_company_update', args=(self.slug,))


class Customer(TimeStampedModel):

    # Fields
    account_number = models.CharField(_(u'account number'), max_length=100)
    credit_limit = models.DecimalField(_(u'credit limit'), max_digits=12, decimal_places=4, default=0, help_text=_(u"Credit limit - Negative value to allow discovery."))
    low_credit_alert = models.DecimalField(_(u'low credit level alert'), max_digits=12, decimal_places=4, default="10", help_text=_(u"Low credit limit alert."))
    max_calls = models.PositiveIntegerField(_(u'max simultaneous calls'), default=1, help_text=_(u"maximum simultaneous calls allowed for this customer account."))
    calls_per_second = models.PositiveIntegerField(_(u'max calls per second'), default=10, help_text=_(u"maximum calls per seconds allowed for this customer account."))
    customer_enabled = models.BooleanField(_(u"customer enabled / disabled"), default=True)
    blocking_credit_limit = models.BooleanField(_(u"block calls if credit limit is reached"), default=True)
    customer_balance = models.DecimalField(_(u'customer balance'), max_digits=12, decimal_places=6, default=0, help_text=_(u"actual customer balance."))
    customer_balance_update = models.BooleanField(_(u"customer balance is updated after each call"), default=True)

    # Relationship Fields
    company = models.OneToOneField(
        'pyfb_company.Company',
        on_delete=models.CASCADE, related_name="customers"
    )

    class Meta:
        db_table = 'pyfb_customer'
        ordering = ('company',)
        verbose_name = _(u'customer')
        verbose_name_plural = _(u'customers')

    def __str__(self):
        return u'%s' % self.company

    def get_absolute_url(self):
        return reverse('pyfb-company:pyfb_company_customer_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('pyfb-company:pyfb_company_customer_update', args=(self.pk,))

    def colored_name(self):
        if self.customer_enabled == False:
            color = "orange"
        else:
            color = "green"
        return " <span style=color:%s>%s</span>" % (color, self.name)
    colored_name.allow_tags = True


class Provider(TimeStampedModel):

    # Fields
    supplier_enabled = models.BooleanField(_(u"provider enabled / disabled"), default=True)
    supplier_balance = models.DecimalField(_(u'provider balance'), max_digits=12, decimal_places=6, default=0, help_text=_(u"actual provider balance."))
    provider_balance_update = models.BooleanField(_(u"provider balance is updated after each call"), default=False)

    # Relationship Fields
    company = models.OneToOneField(
        'pyfb_company.Company',
        on_delete=models.CASCADE, related_name="providers"
    )

    class Meta:
        db_table = 'pyfb_provider'
        ordering = ('company',)
        verbose_name = _(u'provider')
        verbose_name_plural = _(u'providers')

    def __str__(self):
        return u'%s' % self.company

    def get_absolute_url(self):
        return reverse('pyfb-company:pyfb_company_provider_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('pyfb-company:pyfb_company_provider_update', args=(self.pk,))

    def colored_name(self):
        if self.supplier_enabled == False:
            color = "orange"
        else:
            color = "green"
        return " <span style=color:%s>%s</span>" % (color, self.name)
    colored_name.allow_tags = True


class CompanyBalanceHistory(TimeStampedModel):

    # Choices
    OPERATION_TYPE_CHOICES = (
        ('customer', _(u"operation on customer account")),
        ('provider', _(u"operation on provider account")),
    )

    # Fields
    amount_debited = models.DecimalField(_(u'amount debited'), max_digits=12, decimal_places=4)
    amount_refund = models.DecimalField(_(u'amount refund'), max_digits=12, decimal_places=4)
    customer_balance = models.DecimalField(_(u'customer balance'), max_digits=12, decimal_places=4, default=0, help_text=_(u"resulting customer balance."))
    supplier_balance = models.DecimalField(_(u'provider balance'), max_digits=12, decimal_places=4, default=0, help_text=_(u"resulting provider balance."))
    operation_type = models.CharField(_(u"operation type"), max_length=10, choices=OPERATION_TYPE_CHOICES, default='customer')
    external_desc = models.CharField(_(u'public description'), max_length=255, blank=True)
    internal_desc = models.CharField(_(u'internal description'), max_length=255, blank=True)

    # Relationship Fields
    company = models.ForeignKey(
        'pyfb_company.Company',
        on_delete=models.CASCADE, related_name="companys", verbose_name=_(u"company")
    )

    class Meta:
        db_table = 'pyfb_company_balance_history'
        ordering = ('company', '-created')
        verbose_name = _(u'company balance history')
        verbose_name_plural = _(u'company balance history')

    def __str__(self):
        return u"%s %s %s %s" % (self.company,
                                 self.amount_debited,
                                 self.amount_refund,
                                 self.operation_type)

    def get_absolute_url(self):
        return reverse('pyfb-company:pyfb_company_companybalancehistory_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('pyfb-company:pyfb_company_companybalancehistory_update', args=(self.pk,))

pyfb_company/forms.py
from django import forms
from .models import Company, Customer, Provider, CompanyBalanceHistory


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name', 'address', 'contact_name', 'contact_phone']


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['account_number', 'credit_limit', 'low_credit_alert', 'max_calls', 'calls_per_second', 'customer_enabled', 'company']


class ProviderForm(forms.ModelForm):
    class Meta:
        model = Provider
        fields = ['supplier_enabled', 'company']


class CompanyBalanceHistoryForm(forms.ModelForm):
    class Meta:
        model = CompanyBalanceHistory
        fields = ['amount_debited', 'amount_refund', 'customer_balance', 'supplier_balance', 'operation_type', 'external_desc', 'internal_desc', 'company']

pyfb_company/views.py
# -*- coding: utf-8 -*-
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from .models import Company, Customer, Provider, CompanyBalanceHistory
from .forms import CompanyForm, CustomerForm, ProviderForm, CompanyBalanceHistoryForm


class CompanyListView(ListView):
    model = Company


class CompanyCreateView(CreateView):
    model = Company
    form_class = CompanyForm


class CompanyDetailView(DetailView):
    model = Company


class CompanyUpdateView(UpdateView):
    model = Company
    form_class = CompanyForm


class CustomerListView(ListView):
    model = Customer


class CustomerCreateView(CreateView):
    model = Customer
    form_class = CustomerForm


class CustomerDetailView(DetailView):
    model = Customer


class CustomerUpdateView(UpdateView):
    model = Customer
    form_class = CustomerForm


class ProviderListView(ListView):
    model = Provider


class ProviderCreateView(CreateView):
    model = Provider
    form_class = ProviderForm


class ProviderDetailView(DetailView):
    model = Provider


class ProviderUpdateView(UpdateView):
    model = Provider
    form_class = ProviderForm


class CompanyBalanceHistoryListView(ListView):
    model = CompanyBalanceHistory


class CompanyBalanceHistoryCreateView(CreateView):
    model = CompanyBalanceHistory
    form_class = CompanyBalanceHistoryForm


class CompanyBalanceHistoryDetailView(DetailView):
    model = CompanyBalanceHistory


class CompanyBalanceHistoryUpdateView(UpdateView):
    model = CompanyBalanceHistory
    form_class = CompanyBalanceHistoryForm

pyfb_company/templates/pyfb_company/company_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-company:pyfb_company_company_list' %}">{% trans "company listing" %}</a></p>
<table class="table">
<tr><td>{% trans "name" %}</td><td>{{ object.name }}</td></tr>
<tr><td>{% trans "created" %}</td><td>{{ object.created }}</td></tr>
<tr><td>{% trans "modified" %}</td><td>{{ object.modified }}</td></tr>
<tr><td>{% trans "address" %}</td><td>{{ object.address }}</td></tr>
<tr><td>{% trans "contact name" %}</td><td>{{ object.contact_name }}</td></tr>
<tr><td>{% trans "contact phone" %}</td><td>{{ object.contact_phone }}</td></tr>
<tr><td>{% trans "customer balance" %}</td><td>{{ object.customer_balance }}</td></tr>
<tr><td>{% trans "supplier balance" %}</td><td>{{ object.supplier_balance }}</td></tr>
<tr><td>{% trans "created" %}</td><td>{{ object.created }}</td></tr>
<tr><td>{% trans "modified" %}</td><td>{{ object.modified }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">{% trans "edit company" %}</a>

{% endblock %}

pyfb_company/templates/pyfb_company/company_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-company:pyfb_company_company_list' %}">{% trans "company listing" %}</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">{% trans "submit" %}</button>
</form>
{% endblock %}

pyfb_company/templates/pyfb_company/company_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-company:pyfb_company_company_list' %}">{% trans "company listing" %}</a></p>
<table class="table">
<tr>
<td>ID</td><td>{% trans "link" %}</td>
    <td>{% trans "name" %}</td>
    <td>{% trans "contact name" %}</td>
    <td>{% trans "contact phone" %}</td>
    <td>{% trans "customer balance" %}</td>
    <td>{% trans "supplier balance" %}</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.name }}</td>
    <td>{{ object.contact_name }}</td>
    <td>{{ object.contact_phone }}</td>
    <td>{{ object.customer_balance }}</td>
    <td>{{ object.supplier_balance }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-company:pyfb_company_company_create' %}">{% trans "create new company" %}</a>
{% endblock %}

pyfb_company/templates/pyfb_company/companybalancehistory_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-company:pyfb_company_companybalancehistory_list' %}">{% trans "balance history" %}</a></p>
<table class="table">
<tr><td>{% trans "amount debited" %}</td><td>{{ object.amount_debited }}</td></tr>
<tr><td>{% trans "amount refund" %}</td><td>{{ object.amount_refund }}</td></tr>
<tr><td>{% trans "customer balance" %}</td><td>{{ object.customer_balance }}</td></tr>
<tr><td>{% trans "supplier balance" %}</td><td>{{ object.supplier_balance }}</td></tr>
<tr><td>{% trans "operation type" %}</td><td>{{ object.operation_type }}</td></tr>
<tr><td>{% trans "external description" %}</td><td>{{ object.external_desc }}</td></tr>
<tr><td>{% trans "internal description" %}</td><td>{{ object.internal_desc }}</td></tr>
<tr><td>{% trans "created" %}</td><td>{{ object.created }}</td></tr>
<tr><td>{% trans "modified" %}</td><td>{{ object.modified }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">{% trans "edit" %}</a>

{% endblock %}

pyfb_company/templates/pyfb_company/companybalancehistory_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-company:pyfb_company_companybalancehistory_list' %}">{% trans "balance history" %}</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">{% trans "submit" %}</button>
</form>
{% endblock %}

pyfb_company/templates/pyfb_company/companybalancehistory_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-company:pyfb_company_companybalancehistory_list' %}">balance history" %}</a></p>
<table class="table">
<tr>
<td>ID</td><td>{% trans "link" %}</td>
    <td>{% trans "amount debited" %}</td>
    <td>{% trans "amount refund" %}</td>
    <td>{% trans "customer balance" %}</td>
    <td>{% trans "supplier balance" %}</td>
    <td>{% trans "operation type" %}</td>
    <td>{% trans "external description" %}</td>
    <td>{% trans "internal description" %}</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.amount_debited }}</td>
    <td>{{ object.amount_refund }}</td>
    <td>{{ object.customer_balance }}</td>
    <td>{{ object.supplier_balance }}</td>
    <td>{{ object.operation_type }}</td>
    <td>{{ object.external_desc }}</td>
    <td>{{ object.internal_desc }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-company:pyfb_company_companybalancehistory_create' %}">Create new entry" %}</a>
{% endblock %}

pyfb_company/templates/pyfb_company/customer_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-company:pyfb_company_customer_list' %}">{% trans "customer listing" %}</a></p>
<table class="table">
<tr><td>{% trans "account number" %}</td><td>{{ object.account_number }}</td></tr>
<tr><td>{% trans "credit limit" %}</td><td>{{ object.credit_limit }}</td></tr>
<tr><td>{% trans "low credit alert" %}</td><td>{{ object.low_credit_alert }}</td></tr>
<tr><td>{% trans "max simultaneous calls" %}</td><td>{{ object.max_calls }}</td></tr>
<tr><td>{% trans "calls per second limit" %}</td><td>{{ object.calls_per_second }}</td></tr>
<tr><td>{% trans "enabled" %}</td><td>{{ object.customer_enabled }}</td></tr>
<tr><td>{% trans "created" %}</td><td>{{ object.created }}</td></tr>
<tr><td>{% trans "modified" %}</td><td>{{ object.modified }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">{% trans "edit customer" %}</a>

{% endblock %}

pyfb_company/templates/pyfb_company/customer_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-company:pyfb_company_customer_list' %}">{% trans "customer listing" %}</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">{% trans "submit" %}</button>
</form>
{% endblock %}

pyfb_company/templates/pyfb_company/customer_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-company:pyfb_company_customer_list' %}">{% trans "customer listing" %}</a></p>
<table class="table">
<tr>
<td>ID</td><td>{% trans "link" %}</td>
    <td>{% trans "credit_limit" %}</td>
    <td>{% trans "max_calls" %}</td>
    <td>{% trans "calls_per_second" %}</td>
    <td>{% trans "customer_enabled" %}</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.credit_limit }}</td>
    <td>{{ object.low_credit_alert }}</td>
    <td>{{ object.max_calls }}</td>
    <td>{{ object.calls_per_second }}</td>
    <td>{{ object.customer_enabled }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-company:pyfb_company_customer_create' %}">{% trans "create new customer" %}</a>
{% endblock %}

pyfb_company/templates/pyfb_company/provider_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-company:pyfb_company_provider_list' %}">{% trans "provider listing" %}</a></p>
<table class="table">
<tr><td>{% trans "enabled" %}</td><td>{{ object.supplier_enabled }}</td></tr>
<tr><td>{% trans "created" %}</td><td>{{ object.created }}</td></tr>
<tr><td>{% trans "modified" %}</td><td>{{ object.modified }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">{% trans "edit provider" %}</a>

{% endblock %}

pyfb_company/templates/pyfb_company/provider_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-company:pyfb_company_provider_list' %}">{% trans "provider listing" %}</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">{% trans "submit" %}</button>
</form>
{% endblock %}

pyfb_company/templates/pyfb_company/provider_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-company:pyfb_company_provider_list' %}">{% trans "provider listing" %}</a></p>
<table class="table">
<tr>
<td>ID</td><td>{% trans "link" %}</td>
    <td>{% trans "enabled" %}</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.supplier_enabled }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-company:pyfb_company_provider_create' %}">{% trans "create new provider" %}</a>
{% endblock %}